name: ci
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - name: Install Dependencies
        run: yarn install
      - name: Run test
        run: yarn test
      - name: Run building test
        run: yarn build
env:
  YARN_CACHE_FOLDER: .cache/yarn
